config/routes.rb
Rails.application.routes.draw do
  resources :products do
  	resources :reviews
  end

  root :to => "products#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ActiveRecord::Base
	has_many :reviews
	validates :name, :presence => true
	validates :cost, :presence => true
	validates :country, :presence => true


scope :us_made, -> { where({ country: "United States of America"}) }

scope :most_reviewed, -> {(
    select("products.*, count(reviews.id) as reviews_count")
    .joins(:reviews)
    .group("products.id")
    .order("reviews_count DESC")
    .limit(1)
  )}

scope :recently_added, -> {(
    select("products.*")
    .group("products.id")
    .order("created_at DESC")
    .limit(3)
  )}

	
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :product

  validates :author, :presence => true
  validates :rating, :presence => true
  validates :content, :presence => true

  validates :rating, length: { in: 1..5 }
  validates :content, length: { in: 50..250 }

  scope :three_most_recent, -> { order(created_at: :desc).limit(3)}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	def index 
		@products = Product.all
		@us_made = Product.us_made
		@most_reviewed = Product.most_reviewed
		@recently_added = Product.recently_added
		render :index
	end

	def show
		@product = Product.find(params[:id])		
		render :show
	end

	def new
		@product = Product.new
		render :new
	end

	def create
	    @product = Product.new(product_params)
	    if @product.save
	      flash[:success] = "New product added"

	      redirect_to  products_path
	    else
	      render :new
	    end
	  end

	  def edit
	    @product = Product.find(params[:id])
	    render :edit
	  end

	  def update
	    @product = Product.new(product_params)
	    if @product.update(product_params)
	      redirect_to  products_path
	    else
	      render :edit
	    end
	  end

	  def destroy
	    @product = Product.find(params[:id])
	    @product.destroy
	    flash[:danger] = "Product deleted"
	    redirect_to  products_path
	  end


	private
	  def product_params
	    params.require(:product).permit(:name, :cost, :country)
	  end



end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new
  end

  def create
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new(review_params)
    if @review.save
      redirect_to product_path(@review.product)
    else
      render :new
    end
  end

private
  def review_params
    params.require(:review).permit(:author, :rating, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
<h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li> <%= message %> </li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mario Shop</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div class="container">
      <div class="jumbotron">
          <h1>Mario's Speciality Food Products</h1>
          <p>Track <span class="label label-info">products ,reviews, costs</span> and much more.. </p>
        </div>

      <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>">
            <%= value %>
      </div>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/products/_form.html.erb
<%= render "layouts/errors", :object => @product %>

<%= form_for @product do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :cost %>
  <%= f.text_field :cost %>
  <%= f.label :country  %>
  <%= f.text_field :country %>
  <%= f.submit %>
<% end %>

app/views/products/edit.html.erb
<h1>Edit Product</h1>

<%= render "form" %>

app/views/products/index.html.erb
<h1>Products</h1>

  

<div class="container">
      <br/>
    <table>
      <tr>
        <th>Product Name</th>
        <th>Cost</th>
        <th>Country of origin</th>
      </tr>

	<% @products.each do |product| %>

      <tr>
        <td> <%= link_to product.name, product_path(product) %></td>
        <td> $ <%= product.cost %></td>
        <td><%= product.country %></td>
      </tr>
   
  <% end %>
   </table>


<h2>USA Products</h2>
<% if @us_made.any? %>
  <% @us_made.each do |product| %>
    <ul>
      <li><%= link_to product.name, product_path(product) %></li>
    </ul>
  <% end %>
<% else %>
  <p>No US product right now!!!</p>
<% end %>

<% if false %>

<h2>Added recently</h2>
<% if @recently_added.any? %>
  <% @recently_added.each do |product| %>
    <ul>
      <li><%= link_to product.name, product_path(product) %></li>
    </ul>
  <% end %>
<% else %>
  <p>No recent product right now!!!</p>
<% end %>

<h2>Most reviewed</h2>
<% if @most_reviewed.any? %>
  <% @most_reviewed.each do |product| %>
    <ul>
      <li><%= link_to product.name, product_path(product) %></li>
    </ul>
  <% end %>
<% else %>
  <p>No most reviewed products right now!!!</p>
<% end %>

<% end %>
 
  <br>

<%= link_to "New Product", new_product_path %>

    
  </div>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render "form" %>

app/views/products/show.html.erb
<h3>What people are saying about <%= @product.name %></h3>
<br><br><br>

    <% if @product.reviews.any? %>
    <% @product.reviews.each do |review| %>
      <div class="well reviews">
        <h3><%= review.author%></h3>
        <%= review.rating%> / 5 stars
        <hr>
        <blockquote class="blockquote">
          <p>"<%= review.content %>"</p>
        </blockquote>
      </div>
    <% end %>
<% else %>
  <p>No reviews for this <%= @product.name %></p>
<% end %>

<p><%= link_to "Add a review", new_product_review_path(@product) %></p>

<p><%= link_to "Edit", edit_product_path(@product) %></p>
<p><%= link_to "Delete", product_path(@product),
                         :data => {:confirm => "You sure?",
                                   :method => "delete"} %></p>

app/views/reviews/_form.html.erb
<%= render "layouts/errors", :object => @review %>

<%= form_for [ @product, @review ] do |f| %>
  <%= f.label :author %>
  <%= f.text_field :author %>
  <%= f.label :rating %>
  <%= f.text_field :rating %>
  <%= f.label :content  %>
  <%= f.text_field :content %>
  <%= f.submit %>
<% end %>

app/views/reviews/new.html.erb
<h1>New Review for <%= @product.name %></h1>

<%= render 'form' %>